spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.1.29:53306/fibo_rule?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
      username: root
      password: 4paradigm_test