export default [
    {
        nodeType: 1,
        nodeName: '开始',
        edges: 3,
        shape: 'polyNode',
        width: 50,
        height: 50,
        fillStyle:'#fff',
        listShow:false,
    },
    {
        nodeType: 2,
        nodeName: '结束',
        shape: 'circle',
        size: 50,
        fillStyle:'#fff',
        listShow:true,
    },
    {
        nodeType: 3,
        nodeName: '普通节点',
        shape: 'circle',
        size: 50,
        fillStyle:'#fff',
        listShow:true,
    },
    {
        nodeType: 4,
        nodeName: 'if节点',
        edges: 4,
        shape: 'polyNode',
        width: 70,
        height: 50,
        fillStyle:'#fff',
        listShow:true,
    },
    {
        nodeType: 5,
        nodeName: 'switch',
        shape: 'polyNode',
        edges: 5,
        width: 50,
        height: 50,
        fillStyle:'#fff',
        haveMoreChildren:true,
        listShow:true,
    },
    {
        nodeType: 6,
        nodeName: '并行',
        shape: 'circle',
        size: 50,
        fillStyle:'#fff',
        listShow:true,
        haveMoreChildren:true,
        deriveNode:7
    },
    {
        nodeType: 7,
        nodeName: '聚合',
        shape: 'circle',
        size: 50,
        fillStyle:'#fff',
        listShow:false,
    },
    
]